version: "3.9"

services:
  server:
    build: .
    depends_on:
      - database
    environment:
      POSTGRES_URL: "postgres://root:root@database:5432/novo?sslmode=disable"
    ports:
      - "7001:8080"
    volumes:
      - data:/app/static/images
  database:
    image: postgres:14.0
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: novo
      PGDATA: /var/lib/postgresql/data/sub/
    ports:
      - "5432:5432"
  sqlc:
    image: kjconroy/sqlc
    volumes:
      - ./:/src
    working_dir: /src
    command: "generate"
  migrate:
    image: migrate/migrate
    depends_on:
      - database
    volumes:
      - ./static/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://root:root@database:5432/novo?sslmode=disable", "up" ]

volumes:
  data:
